# link_syscfg_libs.cmake
# Read library entries generated by SysConfig in device.lds.genlibs.
# Link libraries that exist and report a clear error for missing ones.

function(link_syscfg_libs TARGET TI_SDK_ROOT GENLIBS_FILE)
    if(NOT EXISTS "${GENLIBS_FILE}")
        return()
    endif()

    file(STRINGS "${GENLIBS_FILE}" INPUT_LINES REGEX "INPUT")
    list(LENGTH INPUT_LINES LINE_COUNT)
    message(STATUS "link_syscfg_libs: ${LINE_COUNT} libraries from SysConfig")

    set(MISSING "")

    foreach(LINE ${INPUT_LINES})
        # Extract the path by removing the INPUT("...") wrapper.
        string(REPLACE "INPUT(\"" "" LIB_PATH "${LINE}")
        string(REPLACE "\")" "" LIB_PATH "${LIB_PATH}")

        set(FULL_PATH "${TI_SDK_ROOT}/source/${LIB_PATH}")
        if(EXISTS "${FULL_PATH}")
            # Use the full path because driverlib.a has no conventional "lib" prefix.
            target_link_libraries(${TARGET} PRIVATE "${FULL_PATH}")
        else()
            list(APPEND MISSING "${LIB_PATH}")
        endif()
    endforeach()

    if(MISSING)
        message("")
        message("    The following libraries do not exist in the device.lds.genlibs generated by SysConfig:")
        foreach(LIB ${MISSING})
            message("     ${LIB}")
        endforeach()
        message("")
        message("Please disable the corresponding genLib* function in .syscfg, or install the corresponding SDK component")
        message(FATAL_ERROR "Fix the issues above, then reconfigure")
    endif()
endfunction()
