# link_syscfg_libs.cmake
# 读取 SysConfig 生成的 device.lds.genlibs, 逐条检查库文件路径
# 存在则链接，不存在则报错

function(link_syscfg_libs TARGET TI_SDK_ROOT GENLIBS_FILE)
    if(NOT EXISTS "${GENLIBS_FILE}")
        return()
    endif()

    file(STRINGS "${GENLIBS_FILE}" INPUT_LINES REGEX "INPUT")
    list(LENGTH INPUT_LINES LINE_COUNT)
    message(STATUS "link_syscfg_libs: ${LINE_COUNT} libraries from SysConfig")

    set(MISSING "")

    foreach(LINE ${INPUT_LINES})
        # 提取路径: 去除 "INPUT(\"" 前缀和 "\")" 后缀
        string(REPLACE "INPUT(\"" "" LIB_PATH "${LINE}")
        string(REPLACE "\")" "" LIB_PATH "${LIB_PATH}")

        set(FULL_PATH "${TI_SDK_ROOT}/source/${LIB_PATH}")
        if(EXISTS "${FULL_PATH}")
            # 直接传完整路径，避免 -l 命名约定 (driverlib.a 无 lib 前缀)
            target_link_libraries(${TARGET} PRIVATE "${FULL_PATH}")
        else()
            list(APPEND MISSING "${LIB_PATH}")
        endif()
    endforeach()

    if(MISSING)
        message("")
        message("    The following libraries do not exist in the device.lds.genlibs generated by SysConfig:")
        foreach(LIB ${MISSING})
            message("     ${LIB}")
        endforeach()
        message("")
        message("Please disable the corresponding genLib* function in .syscfg, or install the corresponding SDK component")
        message(FATAL_ERROR "Fix the issues above, then reconfigure")
    endif()
endfunction()
